---
  title: "GERALDO: Gerenciamento Genômico e Algorítmico de Fenótipos, Riscos, Diagnósticos e Prognósticos em Dados de Doenças em Brasileiros"
---

Nesta parte, demonstramos como informações da literatura científica internacional podem ser integradas aos dados públicos de saúde dos brasileiros. Atualmente, temos duas categorias de doenças cujos dados buscamos integrar aos dados disponibilizados publicamente da população brasileira: 1. Genômica das doenças neurodegenerativas que acomentem a população durante o envelhecimeto e 2. Genômica de doenças oncológicas.  


#### Identidade étnico-racial dos brasileiros através da herança mitocondrial

* [Herança genética mitocondrial em brasileiros](https://drive.google.com/file/d/1ktjyICrpuEgZq_8Z_7jexouV7oDG2q9A/view?usp=sharing)
* [Herança genética polinésia entre índios botocudos brasileiros](https://drive.google.com/file/d/1w7UFJjQ2cdhwVqcNqj6WS6umQ0YVroAv/view?usp=sharing)

#### Fatores influenciadores de diagnóstico e prognóstico oncológicos

* [Mecanismo epigenético mediado pela enzima TET1 e deposição de marcador 5-hmC ](https://drive.google.com/file/d/1y8cyy0HhmpSU6kGXpiOe6P13pMusR6pl/view?usp=sharing)

* [Transição celular em neuroblastoma](https://drive.google.com/file/d/19RH0wevY3VysdBa_o35loCOIQSrgXU5B/view?usp=sharing)

* [Mecanismo epigenético de resitência de células mesenquimais à imunoterapia](https://drive.google.com/file/d/1cIWfGZvEKQx-o00sxphfrw9LdZdkOCuV/view?usp=sharing)
