<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>05-binary-lr-kmed.knit</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/lumen.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Gerenciamento Genômico e Algorítmico de Fenótipos, Riscos, Diagnósticos e Prognósticos em Dados de Doenças em Brasileiros</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="quokka-bilby.html">
    <span class="fa fa-solid fa-circle-info"></span>
     
    Sobre nós
  </a>
</li>
<li>
  <a href="PmD.html">
    <span class="fa fa-solid fa-people-arrows"></span>
     
    PmD
  </a>
</li>
<li>
  <a href="codigo.html">
    <span class="fa fa-solid fa-laptop-file"></span>
     
    Notebooks de Código
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<p>Previous reference: <a
href="https://www.r-bloggers.com/2020/05/binary-logistic-regression-with-r/"
class="uri">https://www.r-bloggers.com/2020/05/binary-logistic-regression-with-r/</a></p>
<p>Google search: binary logistic regression R Reference:</p>
<p><a href="https://statsandr.com/blog/binary-logistic-regression-in-r/"
class="uri">https://statsandr.com/blog/binary-logistic-regression-in-r/</a></p>
<pre class="r"><code># import and rename dataset
library(kmed)
dat &lt;- heart

# select variables
library(dplyr)
library(maditr)
dat &lt;- dat %&gt;%
  select(
    age,
    sex,
    cp,
    thalach,
    class
  )

# print dataset&#39;s structure
str(dat)</code></pre>
<pre><code>## &#39;data.frame&#39;:    297 obs. of  5 variables:
##  $ age    : num  63 67 67 37 41 56 62 57 63 53 ...
##  $ sex    : logi  TRUE TRUE TRUE TRUE FALSE TRUE ...
##  $ cp     : Factor w/ 4 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;: 1 4 4 3 2 2 4 4 4 4 ...
##  $ thalach: num  150 108 129 187 172 178 160 163 147 155 ...
##  $ class  : int  0 2 1 0 0 0 3 0 2 1 ...
##  - attr(*, &quot;na.action&quot;)= &#39;omit&#39; Named int [1:6] 88 167 193 267 288 303
##   ..- attr(*, &quot;names&quot;)= chr [1:6] &quot;88&quot; &quot;167&quot; &quot;193&quot; &quot;267&quot; ...</code></pre>
<p>For greater readability, we rename the variables cp, thalach and
class with more informative names:</p>
<pre class="r"><code># rename variables
dat &lt;- dat %&gt;%
  rename(
    chest_pain = cp,
    max_heartrate = thalach,
    heart_disease = class
  )</code></pre>
<p>We transform the variables sex and chest_pain into factor and set the
labels accordingly:</p>
<pre class="r"><code># recode sex
dat$sex &lt;- factor(dat$sex,
  levels = c(FALSE, TRUE),
  labels = c(&quot;female&quot;, &quot;male&quot;)
)

# recode chest_pain
dat$chest_pain &lt;- factor(dat$chest_pain,
  levels = 1:4,
  labels = c(&quot;typical angina&quot;, &quot;atypical angina&quot;, &quot;non-anginal pain&quot;, &quot;asymptomatic&quot;)
)</code></pre>
<p>For a binary logistic regression in R, it is recommended that all the
qualitative variables are transformed into factors.</p>
<p>In our case, heart_rate (our dependent variable) is currently encoded
as integer with values ranging from 0 to 4. Therefore, we first classify
it into 2 classes by setting 0 for 0 values and 1 for non-0 values,
using the ifelse() function:</p>
<pre class="r"><code># recode heart_disease into 2 classes
dat$heart_disease &lt;- ifelse(dat$heart_disease == 0,
  0,
  1
)</code></pre>
<p>We then transform it into a factor and set the labels accordingly
using the factor() function:</p>
<pre class="r"><code># set labels for heart_disease
dat$heart_disease &lt;- factor(dat$heart_disease,
  levels = c(0, 1),
  labels = c(&quot;no disease&quot;, &quot;disease&quot;)
)</code></pre>
<p>Keep in mind the order of the levels for your dependent variable, as
it will have an impact on the interpretations. In R, the first level
given by levels() is always taken as the reference level.</p>
<p>In our case, the first level is the absence of the disease and the
second level is the presence of the disease:</p>
<pre class="r"><code>levels(dat$heart_disease)</code></pre>
<pre><code>## [1] &quot;no disease&quot; &quot;disease&quot;</code></pre>
<pre class="r"><code># basic descriptive statistics
summary(dat)</code></pre>
<pre><code>##       age            sex                 chest_pain  max_heartrate  
##  Min.   :29.00   female: 96   typical angina  : 23   Min.   : 71.0  
##  1st Qu.:48.00   male  :201   atypical angina : 49   1st Qu.:133.0  
##  Median :56.00                non-anginal pain: 83   Median :153.0  
##  Mean   :54.54                asymptomatic    :142   Mean   :149.6  
##  3rd Qu.:61.00                                       3rd Qu.:166.0  
##  Max.   :77.00                                       Max.   :202.0  
##     heart_disease
##  no disease:160  
##  disease   :137  
##                  
##                  
##                  
## </code></pre>
<div id="binary-logistic-regression-in-r" class="section level1">
<h1>Binary logistic regression in R</h1>
<div id="quantitative-independent-variable" class="section level2">
<h2>Quantitative independent variable</h2>
<pre class="r"><code># save model
m1 &lt;- glm(heart_disease ~ age,
  data = dat,
  family = &quot;binomial&quot;
)</code></pre>
<p>Results of the model is saved under the object m1. Again, similar to
linear regression, results can be accessed thanks to the summary()
function:</p>
<pre class="r"><code># print results
summary(m1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = heart_disease ~ age, family = &quot;binomial&quot;, data = dat)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -3.05122    0.76862  -3.970  7.2e-05 ***
## age          0.05291    0.01382   3.829 0.000128 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 409.95  on 296  degrees of freedom
## Residual deviance: 394.25  on 295  degrees of freedom
## AIC: 398.25
## 
## Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div id="or-for-age" class="section level2">
<h2>OR for age</h2>
<pre class="r"><code># OR for age
exp(coef(m1)[&quot;age&quot;])</code></pre>
<pre><code>##      age 
## 1.054331</code></pre>
<p>In our case, it corresponds to the probability that a patient of age
0 develops a heart disease, which is equal to:</p>
<pre class="r"><code># prob(heart disease) for age = 0
exp(coef(m1)[1]) / (1 + exp(coef(m1)[1]))</code></pre>
<pre><code>## (Intercept) 
##  0.04516478</code></pre>
<p>This means that, if we trust our model, a newborn is expected to
develops a heart disease with a probability of 4.52%.</p>
<p>For your information, a confidence interval can be computed for any
of the OR using the confint() function. For example, a 95% confidence
interval for the OR for age:</p>
<pre class="r"><code># 95% CI for the OR for age
exp(confint(m1,
  parm = &quot;age&quot;
))</code></pre>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##    2.5 %   97.5 % 
## 1.026699 1.083987</code></pre>
<p>Suppose we would like to predict the probability of developing a
heart disease for a patient aged 30 years old:</p>
<pre class="r"><code># predict probability to develop heart disease
pred &lt;- predict(m1,
  newdata = data.frame(age = c(30)),
  type = &quot;response&quot;
)

# print prediction
pred</code></pre>
<pre><code>##         1 
## 0.1878525</code></pre>
<p>It is predicted that a 30-year-old patient has a 18.79% chance of
developing a heart disease.</p>
<p>Note that if you would like to construct a confidence interval for
this prediction, it can be done by adding the se = TRUE argument in the
predict() function:</p>
<pre class="r"><code># predict probability to develop heart disease
pred &lt;- predict(m1,
  newdata = data.frame(age = c(30)),
  type = &quot;response&quot;,
  se = TRUE
)

# print prediction
pred$fit</code></pre>
<pre><code>##         1 
## 0.1878525</code></pre>
<pre class="r"><code># 95% confidence interval for the prediction
lower &lt;- pred$fit - (qnorm(0.975) * pred$se.fit)
upper &lt;- pred$fit + (qnorm(0.975) * pred$se.fit)
c(lower, upper)</code></pre>
<pre><code>##          1          1 
## 0.07873357 0.29697138</code></pre>
<p>If you are a frequent reader of the blog, you are probably know that
I like visualizations. The plot_model() function available in the
{sjPlot} R package does a good job of visualizing results of the
model:</p>
<pre class="r"><code># load package
library(&quot;sjPlot&quot;)

# plot
plot_model(m1,
  type = &quot;pred&quot;,
  terms = &quot;age&quot;
) #+ labs(y = &quot;Prob(heart disease)&quot;)</code></pre>
<pre><code>## Data were &#39;prettified&#39;. Consider using `terms=&quot;age [all]&quot;` to get smooth
##   plots.</code></pre>
<p><img src="05-binary-lr-kmed_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
</div>
</div>
<div id="qualitative-independent-variable" class="section level1">
<h1>Qualitative independent variable</h1>
<pre class="r"><code># save model
m2 &lt;- glm(heart_disease ~ sex,
  data = dat,
  family = &quot;binomial&quot;
)

# print results
summary(m2)</code></pre>
<pre><code>## 
## Call:
## glm(formula = heart_disease ~ sex, family = &quot;binomial&quot;, data = dat)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -1.0438     0.2326  -4.488 7.18e-06 ***
## sexmale       1.2737     0.2725   4.674 2.95e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 409.95  on 296  degrees of freedom
## Residual deviance: 386.12  on 295  degrees of freedom
## AIC: 390.12
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code># OR for sex
exp(coef(m2)[&quot;sexmale&quot;])</code></pre>
<pre><code>##  sexmale 
## 3.573933</code></pre>
<p>We can also visualize these results thanks to the plot_model()
function:</p>
<pre class="r"><code># plot
plot_model(m2,
  type = &quot;pred&quot;,
  terms = &quot;sex&quot;
) #+</code></pre>
<p><img src="05-binary-lr-kmed_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<pre class="r"><code>  #labs(y = &quot;Prob(heart disease)&quot;)</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
